apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://ivan-nemkovich.github.io/project-sa/'
    targetRevision: 6.0
    chart: wp_project
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: project
  syncPolicy:
    automated:
      prune: true
