---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wp_project.fullname" . }}-pvc
  labels:
    app: {{ include "wp_project.fullname" . }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi