apiVersion: v1
kind: Service
metadata:
  name: {{ include "wp_project.fullname" . }}
  labels:
    app: {{ include "wp_project.fullname" . }}
    tier: {{ .Values.tier }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "wp_project.fullname" . }}